Use react@next and react-dom@next
camwest/react-slot-fill pull request #5
Opened 2017-03-16 19:38 UTC by rogeliog

I might be wrong here 😄 

The reason why there is a hardcoded `node_modules/react` and `node_modules/react-dom` is because of Fiber right? I changed it to use `react@next` which is now `16-alpha`.

2017-03-16 20:04 UTC, rogeliog commented on package.json
> +  "dependencies": {
Should this just be a dev dependency?

2017-03-16 22:30 UTC, camwest requested changes

2017-03-16 22:30 UTC, camwest commented on package.json
> +  "dependencies": {
Yeah the pattern I've been using is to make react a peer and a dev dependency. Can you swap it to that?

2017-03-17 00:09 UTC, rogeliog commented on package.json
> +  "dependencies": {
I agree but right now the demo is inside of the app, so `npm start` depends on having access to `react`... Maybe extracting the demo directory might be a good solution, with this we can add it as `peerDependency` to `react-slot-fill` and as `dependency` to the demo.

2017-03-17 01:12 UTC, camwest commented on package.json
> +  "dependencies": {
Why not just add it as a peer/dev dependency and then the demo will still build locally webpack doesn't care if something is a dev or real dependency. 

Then when you npm install react-slot-fill it won't try to bring React with it...

I agree in the long run with moving the demos but in the short run I think it's no big deal.

2017-03-18 00:03 UTC, rogeliog commented on package.json
> +  "dependencies": {
Awesome!

2017-03-18 04:03 UTC, camwest approved these changes

2017-03-18 04:03 UTC, merged